[project]
name = "lianghua"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "akshare>=1.18.20",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
]
